### ISSUE TITLE
Siphon should be able to target specific github files in the registry

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#179]
**Describe the solution you'd like**
It would be awesome to be able to just request a specific file from a repo using a github URI or some other type of configuration

**Describe alternatives you've considered**
The only alternative would be to register the repo with a massive inline ignore configuration to ignore everything but the file described

OR

To register the repo with a (currently non-existant) `include` configuration

**Additional context**
Something like this in the registry would be amazing..

```yaml
sourceType: github
sourceProperties:
  name: myrepo
  owner: owner
  file(s): https://github.com/bcgov/devhub-app-web/blob/master/docs/Readme.md
```

**Comment by patricksimonian** [comment]
so as a correction to the files configuration. The **Github Contents API V3** accepts a **path** to a file.
The configuration would need to look more like..

```yaml
sourceType: github
sourceProperties:
  name: myrepo
  owner: owner
  file(s): docs/Readme.md
````

notice it is just the path to file based off of the root
