### ISSUE TITLE
Add Redhat DevSecOps Victoria Event

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#787]
Add this as a card in events
```yaml
url: http://redhatdays.ca/FY19/BERHDVictoria/
image: http://redhatdays.ca/FY19/BERHDVictoria/public/assets/themes/frontend/images/logo_footer.png
resourceType: Events
description: The Red Hat DevSecOps Workshop is a unique hands-on experience for building, deploying, and securing containerized cloud-native applications using industry-standard open source technologies.
```
